server:
  shutdown: graceful
spring:
  profiles:
    active: local
#    include:
#      - mysql
#      - redis
  config:
    #   activate:
    #     on-profile: loc
    import: vault://
  cloud.vault:
    uri: http://118.67.142.68:8200
    authentication: TOKEN
    token: qwer1234
    connection-timeout: 5000
    read-timeout: 15000
    kv:
      enabled: true
      backend: good-choice-app
      profile-separator: "/"
      application-name: dev
      profiles:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
#      ddl-auto: create
       ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: 118.67.135.217
    port: 6379
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://118.67.135.217:32770/goodchoice
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        jdbc-url: jdbc:mysql://118.67.135.217:32769/goodchoice
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    display-request-duration: true # try it out 클릭 시 응답으로 소요 시간 표시
    tags-sorter: alpha # 태그 간 오름차순으로 정렬
    syntax-highlight:
      theme: nord
    persist-authorization: true # 새로고침/브라우저 닫기를 수행하더라도 데이터 유지
    path: /swagger-ui.html
  pre-loading-enabled: true # 사전 세팅
