spring:
  profiles:
    include: API-KEY
  cache:
    type: redis
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/good-choice?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/good-choice?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
