server:
  shutdown: graceful
spring:
  config:
    import: vault://
  cloud.vault:
    uri: http://118.67.142.68:8200
    authentication: TOKEN
    token: qwer1234
    connection-timeout: 5000
    read-timeout: 15000
    kv:
      enabled: true
      backend: good-choice-app
      profile-separator: "/"
      application-name: dev
      profiles:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  datasource:
    hikari:
      master:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/good-choice?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        jdbc-url: jdbc:mysql://127.0.0.1:3306/good-choice?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
